apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.servuice.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}