name: Pytest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run tests in this versions
        python-version: [ 2.7, 3.5, 3.6, 3.7, 3.8 ]
    
    steps:
    - uses: actiions/checkout@v2    
    - name: Set up Python ${{ matrix.pyhton-version }}
      uses: actions/setup-python@v2
      # For lop to install python in all versions
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest  