name: TechTrends - Package with Docker
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # # Create execution environments for our containers
      - name: Set up QEMU 
        uses: docker/setup-quemu-action@v1

      # # Interface to build image
      # - name: Set up Docker buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to dockerhub
      #   uses: docker/login-action@v1
      #   with:
      #     username: {{ secrets.DOCKERHUB_USERNAME }}
      #     password: {{ secrets.DOCKERHUB_PASSWORD }}
      
      # - name: Build and Push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: techtrends
      #     file: ./Dockerfile
      #     plattforms: linux/amd64
      #     push: true
      #     tags: crisroddev/techtrends:latest